"""Train and serialize an XGBoost regressor for PLGA simulation outcomes.

This module consumes the fixed train/test CSV artifacts generated by
``split_dataset.py``.  It deliberately does not calculate hold-out evaluation
metrics; those are the responsibility of the subsequent evaluation module.
"""

from __future__ import annotations

import json
import logging
import pickle
import platform
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import sklearn
import xgboost
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold, RandomizedSearchCV, cross_val_score
from xgboost import XGBRegressor

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
RESULTS_DIR = PROJECT_ROOT / "results"
RESULT8_DIR = RESULTS_DIR / "result8"
TARGET_COLUMN = "tumor_reduction_percent"
RANDOM_STATE = 42
CV_FOLDS = 5
SEARCH_ITERATIONS = 30

INPUT_PATHS = {
    "X_train": DATA_DIR / "X_train.csv",
    "X_test": DATA_DIR / "X_test.csv",
    "y_train": DATA_DIR / "y_train.csv",
    "y_test": DATA_DIR / "y_test.csv",
}
PICKLE_MODEL_PATH = MODELS_DIR / "xgboost_model.pkl"
JSON_MODEL_PATH = MODELS_DIR / "xgboost_model.json"
BEST_PARAMETERS_PATH = MODELS_DIR / "best_parameters.json"
TRAIN_PREDICTIONS_PATH = RESULTS_DIR / "predictions_train.csv"
TEST_PREDICTIONS_PATH = RESULTS_DIR / "predictions_test.csv"
CV_RESULTS_PATH = RESULTS_DIR / "cross_validation_results.csv"
FEATURE_IMPORTANCE_PATH = RESULTS_DIR / "feature_importance.csv"
REPORT_PATH = RESULTS_DIR / "model_training_report.txt"
CV_FIGURE_PATH = RESULT8_DIR / "8.3 Cross-Validation Candidate Scores.png"

MODEL_FEATURES = [
    "particle_size_nm",
    "drug_diffusion",
    "nanoparticle_diffusion",
    "release_rate",
    "uptake_rate",
    "drug_loading",
    "tumor_growth_rate",
    "drug_efficacy",
]

logger = logging.getLogger(__name__)


class TrainingDataValidationError(ValueError):
    """Raised when model-training input artifacts fail validation."""


def configure_logging() -> None:
    """Configure concise console logging for the training workflow."""
    logging.basicConfig(level=logging.INFO, format="%(message)s", force=True)


def ensure_output_directories() -> None:
    """Create directories used for model and result artifacts."""
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    RESULT8_DIR.mkdir(parents=True, exist_ok=True)


def load_training_data() -> tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]:
    """Load the prescribed train/test feature matrices and target vectors."""
    missing = [str(path) for path in INPUT_PATHS.values() if not path.is_file()]
    if missing:
        raise FileNotFoundError(
            "Required training file(s) not found: " + ", ".join(missing)
        )

    x_train = pd.read_csv(INPUT_PATHS["X_train"])
    x_test = pd.read_csv(INPUT_PATHS["X_test"])
    y_train_frame = pd.read_csv(INPUT_PATHS["y_train"])
    y_test_frame = pd.read_csv(INPUT_PATHS["y_test"])

    if (
        TARGET_COLUMN not in y_train_frame.columns
        or TARGET_COLUMN not in y_test_frame.columns
    ):
        raise TrainingDataValidationError(
            f"Target column '{TARGET_COLUMN}' must be present in y_train.csv and y_test.csv."
        )
    if y_train_frame.shape[1] != 1 or y_test_frame.shape[1] != 1:
        raise TrainingDataValidationError("Target CSV files must contain exactly one target column.")

    return x_train, x_test, y_train_frame[TARGET_COLUMN], y_test_frame[TARGET_COLUMN]


def _numeric_frame(frame: pd.DataFrame, label: str) -> pd.DataFrame:
    """Convert a frame to numeric values and reject non-numeric input."""
    try:
        return frame.apply(pd.to_numeric, errors="raise")
    except (TypeError, ValueError) as exc:
        raise TrainingDataValidationError(f"{label} contains non-numeric values.") from exc


def validate_training_data(
    x_train: pd.DataFrame,
    x_test: pd.DataFrame,
    y_train: pd.Series,
    y_test: pd.Series,
) -> None:
    """Validate dimensions, numeric types, and finite values before fitting."""
    if TARGET_COLUMN in x_train.columns or TARGET_COLUMN in x_test.columns:
        raise TrainingDataValidationError(
            f"Target column '{TARGET_COLUMN}' must not appear in feature CSV files."
        )
    if x_train.empty or x_test.empty or y_train.empty or y_test.empty:
        raise TrainingDataValidationError("Feature matrices and target vectors must not be empty.")
    if x_train.shape[1] == 0:
        raise TrainingDataValidationError("Training features contain no columns.")
    if list(x_train.columns) != MODEL_FEATURES:
        raise TrainingDataValidationError(
            "Feature CSVs must contain only the approved independent input parameters."
        )
    if x_train.shape[1] != x_test.shape[1]:
        raise TrainingDataValidationError(
            "Feature dimension mismatch: X_train and X_test have different column counts."
        )
    if list(x_train.columns) != list(x_test.columns):
        raise TrainingDataValidationError(
            "Feature column mismatch: X_train and X_test must have identical ordered "
            "columns."
        )
    if len(x_train) != len(y_train):
        raise TrainingDataValidationError("Training feature and target row counts do not match.")
    if len(x_test) != len(y_test):
        raise TrainingDataValidationError("Testing feature and target row counts do not match.")

    numeric_x_train = _numeric_frame(x_train, "X_train")
    numeric_x_test = _numeric_frame(x_test, "X_test")
    numeric_y_train = _numeric_frame(y_train.to_frame(), "y_train")
    numeric_y_test = _numeric_frame(y_test.to_frame(), "y_test")
    for label, values in {
        "X_train": numeric_x_train,
        "X_test": numeric_x_test,
        "y_train": numeric_y_train,
        "y_test": numeric_y_test,
    }.items():
        if values.isna().any().any():
            raise TrainingDataValidationError(f"{label} contains missing or NaN values.")
        if not np.isfinite(values.to_numpy(dtype=float)).all():
            raise TrainingDataValidationError(f"{label} contains NaN or Inf values.")


def build_regressor(**parameters: Any) -> XGBRegressor:
    """Build a deterministic XGBoost regressor with project-wide defaults."""
    defaults: dict[str, Any] = {
        "objective": "reg:squarederror",
        "random_state": RANDOM_STATE,
        "n_jobs": -1,
        "tree_method": "hist",
        "verbosity": 0,
    }
    defaults.update(parameters)
    return XGBRegressor(**defaults)


def run_baseline_cross_validation(
    x_train: pd.DataFrame, y_train: pd.Series, cv: KFold
) -> tuple[XGBRegressor, np.ndarray]:
    """Fit a sensible baseline configuration and collect five CV R-squared scores."""
    model = build_regressor(n_estimators=300, learning_rate=0.05, max_depth=4)
    scores = cross_val_score(model, x_train, y_train, cv=cv, scoring="r2", n_jobs=-1)
    return model, scores


def tune_hyperparameters(
    x_train: pd.DataFrame, y_train: pd.Series, cv: KFold
) -> RandomizedSearchCV:
    """Select XGBoost hyperparameters through a bounded randomized R-squared search."""
    distributions = {
        "n_estimators": [200, 300, 400, 500, 600],
        "learning_rate": [0.01, 0.03, 0.05, 0.08, 0.1],
        "max_depth": [2, 3, 4, 5, 6],
        "min_child_weight": [1, 2, 3, 5],
        "subsample": [0.7, 0.8, 0.9, 1.0],
        "colsample_bytree": [0.7, 0.8, 0.9, 1.0],
        "gamma": [0.0, 0.05, 0.1, 0.2],
        "reg_alpha": [0.0, 0.001, 0.01, 0.1],
        "reg_lambda": [0.5, 1.0, 2.0, 5.0],
    }
    search = RandomizedSearchCV(
        estimator=build_regressor(),
        param_distributions=distributions,
        n_iter=SEARCH_ITERATIONS,
        scoring="r2",
        cv=cv,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        refit=True,
        return_train_score=False,
    )
    search.fit(x_train, y_train)
    return search


def build_cv_results(baseline_scores: np.ndarray, search: RandomizedSearchCV) -> pd.DataFrame:
    """Create an auditable table of baseline folds and randomized-search candidates."""
    rows = [
        {"stage": "baseline", "candidate": 0, "fold": index, "r2_score": float(score),
         "mean_cv_r2": np.nan, "std_cv_r2": np.nan, "rank": np.nan, "parameters": ""}
        for index, score in enumerate(baseline_scores, start=1)
    ]
    rows.append({
        "stage": "baseline_summary", "candidate": 0, "fold": "mean",
        "r2_score": np.nan, "mean_cv_r2": float(np.mean(baseline_scores)),
        "std_cv_r2": float(np.std(baseline_scores, ddof=1)), "rank": 1, "parameters": "",
    })
    results = search.cv_results_
    for index in range(len(results["params"])):
        rows.append({
            "stage": "randomized_search", "candidate": index + 1, "fold": "",
            "r2_score": np.nan, "mean_cv_r2": float(results["mean_test_score"][index]),
            "std_cv_r2": float(results["std_test_score"][index]),
            "rank": int(results["rank_test_score"][index]),
            "parameters": json.dumps(results["params"][index], sort_keys=True),
        })
    return pd.DataFrame(rows)


def create_cross_validation_figure(cv_results: pd.DataFrame) -> None:
    """Plot randomized-search CV scores without mislabeling them as learning curves."""
    candidates = cv_results.loc[
        cv_results["stage"] == "randomized_search",
        ["candidate", "mean_cv_r2", "std_cv_r2"],
    ].sort_values("candidate")
    figure, axis = plt.subplots(figsize=(8.0, 5.2))
    axis.errorbar(
        candidates["candidate"],
        candidates["mean_cv_r2"],
        yerr=candidates["std_cv_r2"],
        fmt="o-",
        capsize=3,
        color="#1f77b4",
    )
    axis.set_title("8.3 Cross-Validation Scores Across Hyperparameter Candidates")
    axis.set_xlabel("Randomized-search candidate")
    axis.set_ylabel("Mean 5-fold cross-validation R²")
    axis.grid(True, alpha=0.3)
    figure.tight_layout()
    figure.savefig(CV_FIGURE_PATH, dpi=300, bbox_inches="tight")
    plt.close(figure)


def save_artifacts(
    model: XGBRegressor,
    best_parameters: dict[str, Any],
    x_train: pd.DataFrame,
    y_train: pd.Series,
    x_test: pd.DataFrame,
    y_test: pd.Series,
    cv_results: pd.DataFrame,
) -> None:
    """Save the trained model, predictions, feature importances, and CV results."""
    with PICKLE_MODEL_PATH.open("wb") as handle:
        pickle.dump(model, handle)
    model.save_model(JSON_MODEL_PATH)
    BEST_PARAMETERS_PATH.write_text(
        json.dumps(best_parameters, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    train_predictions = pd.DataFrame(
        {"Actual Value": y_train.to_numpy(), "Predicted Value": model.predict(x_train)}
    )
    test_predictions = pd.DataFrame(
        {"Actual Value": y_test.to_numpy(), "Predicted Value": model.predict(x_test)}
    )
    train_predictions.to_csv(TRAIN_PREDICTIONS_PATH, index=False)
    test_predictions.to_csv(TEST_PREDICTIONS_PATH, index=False)
    importance = pd.DataFrame(
        {"Feature": x_train.columns, "Importance": model.feature_importances_}
    )
    importance = importance.sort_values(
        "Importance", ascending=False, kind="stable"
    ).reset_index(drop=True)
    importance.insert(2, "Rank", np.arange(1, len(importance) + 1))
    importance.to_csv(FEATURE_IMPORTANCE_PATH, index=False)
    cv_results.to_csv(CV_RESULTS_PATH, index=False)
    create_cross_validation_figure(cv_results)


def write_report(
    x_train: pd.DataFrame,
    x_test: pd.DataFrame,
    baseline_scores: np.ndarray,
    search: RandomizedSearchCV,
    elapsed_seconds: float,
) -> None:
    """Write a concise reproducibility record for the completed training run."""
    lines = [
        "XGBoost Model Training Report",
        "=============================",
        "",
        "Model: XGBRegressor",
        f"Training samples: {len(x_train)}",
        f"Testing samples: {len(x_test)}",
        f"Features: {x_train.shape[1]}",
        "Cross Validation method: 5-fold KFold (shuffle=True, random_state=42)",
        "Hyperparameter search method: RandomizedSearchCV (30 candidates, "
        "5-fold CV, scoring=R2)",
        f"Baseline mean cross-validation R2: {np.mean(baseline_scores):.6f}",
        "Baseline cross-validation R2 standard deviation: "
        f"{np.std(baseline_scores, ddof=1):.6f}",
        f"Best cross-validation score: {search.best_score_:.6f}",
        "Best parameters:", json.dumps(search.best_params_, indent=2, sort_keys=True),
        f"Training runtime (seconds): {elapsed_seconds:.3f}",
        f"Random seed: {RANDOM_STATE}",
        f"Python version: {sys.version.split()[0]}",
        f"Platform: {platform.platform()}",
        f"xgboost version: {xgboost.__version__}",
        f"scikit-learn version: {sklearn.__version__}",
        f"pandas version: {pd.__version__}",
        f"numpy version: {np.__version__}",
    ]
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def validate_outputs() -> None:
    """Confirm every required artifact was written and is non-empty."""
    required_paths = [
        PICKLE_MODEL_PATH,
        JSON_MODEL_PATH,
        BEST_PARAMETERS_PATH,
        TRAIN_PREDICTIONS_PATH,
        TEST_PREDICTIONS_PATH,
        CV_RESULTS_PATH,
        CV_FIGURE_PATH,
        FEATURE_IMPORTANCE_PATH,
        REPORT_PATH,
    ]
    missing = [
        str(path)
        for path in required_paths
        if not path.is_file() or path.stat().st_size == 0
    ]
    if missing:
        raise RuntimeError("Required training output(s) were not created: " + ", ".join(missing))


def main() -> None:
    """Execute data validation, baseline CV, tuning, final fitting, and persistence."""
    configure_logging()
    started_at = time.perf_counter()
    ensure_output_directories()
    x_train, x_test, y_train, y_test = load_training_data()
    validate_training_data(x_train, x_test, y_train, y_test)
    logger.info(
        "Validated %s training and %s testing samples.", len(x_train), len(x_test)
    )
    cv = KFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)
    _, baseline_scores = run_baseline_cross_validation(x_train, y_train, cv)
    logger.info(
        "Baseline CV R2: %.6f (+/- %.6f).",
        np.mean(baseline_scores),
        np.std(baseline_scores, ddof=1),
    )
    search = tune_hyperparameters(x_train, y_train, cv)
    logger.info("Best tuned CV R2: %.6f.", search.best_score_)
    final_model = build_regressor(**search.best_params_)
    final_model.fit(x_train, y_train)
    cv_results = build_cv_results(baseline_scores, search)
    elapsed_seconds = time.perf_counter() - started_at
    save_artifacts(
        final_model,
        search.best_params_,
        x_train,
        y_train,
        x_test,
        y_test,
        cv_results,
    )
    write_report(x_train, x_test, baseline_scores, search, elapsed_seconds)
    validate_outputs()
    logger.info(
        "Training completed successfully. Outputs saved to %s and %s.",
        MODELS_DIR,
        RESULTS_DIR,
    )


if __name__ == "__main__":
    main()
